### PR TITLE
Build.ps1: Use minimal distribution instead of standard distribution

### LINKED ISSUE #56: Build.ps1: Use Minimal Distribution instead of Standard Distribution
CEF issue 2169 has been resolved, this means `build.ps1` can use the `Minimal Distribution` instead of the `Standard Distribution` to speed up the download, and as a result, total build time.

https://bitbucket.org/chromiumembedded/cef/issues/2169/support-building-just-libcef_dll_wrapper

### PR DESCRIPTION
**Pull request by merceyz**
Changes:
Download the minimal distribution instead of standard distribution to speed up the total build time

Resolves #56

### CODE REVIEW

**Comment by perlun** [comment]
Thanks. @merceyz, have you tested building with this change and verified that it works as expected?

**Comment by merceyz** [comment]
No, i'm unable to successfully run the build script due to me having VS2017

**Comment by perlun** [comment]
> Also before this PR is merged the CEF version needs to be updated

True. So let's wait on it a while. Thanks anyway, a good start!

**Comment by japj** [comment]
I can confirm that it does not work yet.

The problem is that the CMakeList.txt contains lines with `add_subdirectory(tests/xxxx)` and those testclient sources are not present in the minimal distribution. As a result the CMake generation fails. So we probably need to patch the CMakeList.txt before running it.

**Comment by perlun** [comment]
> I can confirm that it does not work yet.

That's interesting actually! I used a similar approach in my #62 hackish branch, and it _did_ actually work using the minimal distrib. (note: x86 only, I haven't yet built CEF successfully on x64...)

**Comment by merceyz** [comment]
> The problem is that the CMakeList.txt contains lines with add_subdirectory(tests/xxxx) and those testclient sources are not present in the minimal distribution.

It was fixed in https://bitbucket.org/chromiumembedded/cef/commits/cd6b88f7e4bd455445a7619824c2109904be97c5

Which is why I said
> Also before this PR is merged the CEF version needs to be updated

**Comment by japj** [comment]
Ah, ... CEF was updated 3 days ago to fix this very issue. That is a “recent” version indeed ;)

**Comment by amaitland** [comment]
Merged with commit https://github.com/cefsharp/cef-binary/commit/a4a84342dbee54cdf9357f158169a0614cbbe5f8

**Comment by amaitland** [comment]
Reverted changes with commit https://github.com/cefsharp/cef-binary/commit/d654b9b91cd5c314f9cd453d73d0cbb835c77117

Switching to the `Minimal` dist won't be possible just yet as it doesn't contain a debug version of `libcef.dll`, so will have to revisit later.

**Pull request closed without merging**
