### PR TITLE
Add minClientVersion 4.0.0, used by vs2017

### PR DESCRIPTION
**Pull request by lifecoder-phoenix**

### CODE REVIEW

**Comment by amaitland** [comment]
Thanks 👍 Do you have a reference link/supporting article? I haven't had a chance to look into this, link for confirmation would be nice. Thanks

**Comment by lifecoder-phoenix** [comment]
Sure, the first message here: https://github.com/NuGet/Home/issues/4492
"Visual Studio 2017 contains NuGet 4.0.0..."

**Comment by amaitland** [comment]
Great, thanks.

**Comment by CSGitHub2016** [comment]
Console.WriteLine("牛逼！");

**Pull request merged**
