### PR TITLE
Added NoDebug option to avoid debug builds, support zip and 7z archiv…

### PR DESCRIPTION
**Pull request by mitchcapper**
…es with Extension option, and can auto detect build from local file, also better exception handling.

There is one line #565 in the new file, I changed the extract arg to pay attention to paths.  Given the .tar.bz2 format however the tar isn't really in a sub-path so I believe should not cause an actual change.

The exception handling I can also remove, not functionally required but can be helpful for tracking down errors.

### CODE REVIEW

**Comment by amaitland** [comment]
Formatting is a little out, though it's not exactly brilliant across the whole file. I can fix that after merge, might even switch back to using `tabs` as it doesn't make a whole lot of sense to use spaces in this project.

As for `NoDebug`, it kinda sounds like we're disabling debugging for the script, so maybe a more descriptive name to make it clearer that the script is ignoring `CEF Debug` builds?

Once this is merged the `wiki` should probably be updated to include some usage examples, what do you think?

**Comment by mitchcapper** [comment]
NoDebugBuild? NoDebugPackage?  Agree about the wiki.  I am finalizing some performance timing expectations right now with my Dockerfiles which also have several use cases.

**Comment by amaitland** [comment]
Maybe `NoCEFDebugBuild`?

**Comment by amaitland** [comment]
Actually `NoDebugBuild` is probably just fine.

**Comment by mitchcapper** [comment]
Sorry I do try to match whitespace but as it was mixed my normal replace tabs with spaces causes more changes than it resolved.  I manually updated the lines I only changed to spaces (but all for moving back to tabs:)).

**Comment by amaitland** [comment]
Totally understand, it's a mess. Will merge now and test out the changes using `Appveyor` for an updated `CEF` build.

**Comment by amaitland** [comment]
Formatting changed, hopefully it makes things easier going forward.

Had to add an additional check creating the `Nuget` folder, nothing serious, see https://github.com/cefsharp/cef-binary/commit/e3647eac344ae95f04f688d7cffa1bd748d10ab6

Packages build successfully, will upgrade `master` shortly and see how they go.

**Comment by mitchcapper** [comment]
documentation added.

**Pull request merged**
