### PR TITLE
Reset environment variables after each build

### PR DESCRIPTION
**Pull request by kpreisser**
Reset the environment variables (`PATH`, `LIB`, `LIBPATH`, `INCLUDE`) set by `vcvarsall.bat` after each build.
This should avoid generating a too long `PATH` environment variable which could cause an error like "The input line is too long" (as seen in the build after merging #90).

See https://github.com/cefsharp/cef-binary/pull/90#issuecomment-760724416

### CODE REVIEW

**Comment by amaitland** [comment]
Thanks 👍

**Comment by amaitland** [comment]
Build is queued. 

https://ci.appveyor.com/project/cefsharp/cef-binary/builds/37290341

**Comment by kpreisser** [comment]
Looks like the build succeeded :+1:

I can see that version `88.1.2` of `cef.sdk` (which includes the `arm64` libs) was uploaded to MyGet. The `cef.redist` and `chromiumembeddedframework.runtime` were also uploaded, but only for `x64` and `x86` (maybe the `arm64` packages need to be created first).

Thanks!

**Comment by amaitland** [comment]
> The `cef.redist` and `chromiumembeddedframework.runtime` were also uploaded, but only for `x64` and `x86` (maybe the `arm64` packages need to be created first).

For new packages a manual push is required.

I've pushed a `88.1.3` build of `chromiumembeddedframework.runtime.win-arm64` just now.

**Pull request merged**
